- name: Configure Common Playbooks
  hosts: all
  roles:
    - common
  tasks:
    - import_tasks: autofs.yml
    - import_tasks: cockpit.yml
    - import_tasks: nrpe.yml
    - import_tasks: ssh-keys.yml
    - import_tasks: sudoers.yml
    - import_tasks: webmin.yml
    - import_tasks: update.yml