---
# file: k8s-site.yml
- hosts: k8s-cluster
  #gather_facts: no
  become: yes
  roles:
    - { role: docker, tags: docker }
  
- hosts: k8s-master
  #gather_facts: no
  become: yes
  roles:
    - { role: k8s-cluster/master, tags: k8s-master }
  
- hosts: k8s-node
  #gather_facts: no
  become: yes
  roles:
    - { role: k8s-cluster/node, tags: k8s-node }
  
- hosts: k8s-master
  #gather_facts: no
  become: yes
  roles:
    - { role: k8s-cni, tags: k8s-cni }
    - { role: k8s-addon, tags: k8s-addon }