---
# file: k8s-site.yml
- hosts: k8s-cluster
  #gather_facts: no
  become: yes
  roles:
    - { role: docker, tags: docker }
  
- import_playbook: k8s-master.yml
- import_playbook: k8s-node.yml
- import_playbook: k8s-master2.yml