---
# file: k8s-site.yml
- hosts: k8s-cluster
  gather_facts: no
  become: yes
  roles:
    - { role: docker, tags: docker }
  
- hosts: k8s-master
  gather_facts: no
  become: yes
  roles:
    - { role: k8s-cluster/master, tags: master }
  
- hosts: k8s-node
  gather_facts: no
  become: yes
  roles:
    - { role: k8s-cluster/node, tags: node }
  
- hosts: k8s-master
  gather_facts: no
  become: yes
  roles:
    - { role: k8s-cni, tags: cni }
    - { role: k8s-addon, tags: addon }