---
# file: roles/kubeadm/tasks/main.yml
- include_vars: "{{ ansible_os_family }}.yml"
  
- include_tasks: roles/kubeadm/tasks/Debian.yml
  when: ansible_os_family == "Debian"
  
- include_tasks: roles/kubeadm/tasks/RedHat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: roles/kubeadm/tasks/common.yml