---

- name: Install AutoFS
  action: >
    {{ ansible_pkg_mgr }} name=autofs state=installed update_cache=true

- name: Configure auto.master
  lineinfile:
    path: /etc/auto.master
    regexp: '/nfs'
    line: '/nfs    /etc/auto.nfs --timeout=60'

- name: Copy auto.nfs to system
  copy: src=roles/autofs/files/auto.nfs dest=/etc/auto.nfs

- name: Ensure AutoFS is enabled at boot and start the daemon
  systemd:
    name: autofs
    state: started
    enabled: yes
