- name: Install Cockpit
  action: >
    {{ ansible_pkg_mgr }} name=cockpit state=installed update_cache=true

- name: Enable Cockpit in systemd
  systemd: name=cockpit.socket enabled=true
  when: ansible_distribution == "CentOS"

- name: Check state of firewalld and register
  command: /usr/bin/firewall-cmd --state
  register: firewalld_state
  when: ansible_distribution == "CentOS"

- name: Check state of UFW and register
  command: ufw status | grep Status:
  register: ufw_state
  when: ansible_distribution == "Ubuntu"

- name: Modify firewalld
  firewalld: service=cockpit zone=public permanent=true immediate=yes state=enabled offline=true
  when: 
    - ansible_distribution == "CentOS"
    - firewalld_state == "running"

- name: Check state of UFW and register
  command: ufw status | grep Status: | sed 's/Status: //g'
  register: ufw_state
  when: ansible_distribution == "Ubuntu"

- name: Modify UFW
  ufw: rule=allow port=9090 proto=tcp src={{ item }}
  with_items:
    - 192.168.52.0/24
    - 192.168.250.0/24
    - 172.16.0.0/12
  when: 
    - ansible_distribution == "Ubuntu"
    - ufw_state = "active"

- name: Start Cockpit
  systemd: name=cockpit state=started
