---

- name: Set up authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - roles/ssh/files/cy-dsktp01.pub
    - roles/ssh/files/cy-mbp-13-3.pub
    - roles/ssh/files/taius-main.pub
    - roles/ssh/files/util01.pub
