---
- name: Apt Install NRPE and Start Service
  apt: pkg=nagios-nrpe-server state=installed update_cache=true
  notify:
   - Start NRPE

- name: Apt Install Nagios-Plugins
  apt: pkg=nagios-plugins state=installed 
  
- name: Install lm-sensors
  apt: pkg=lm-sensors state=installed

- name: Add Nagios Server to allowed_hosts in nrpe.cfg
  lineinfile: dest=/etc/nagios/nrpe.cfg state=present regexp='^allowed_hosts=127\.0\.0\.1' line='allowed_hosts=127.0.0.1,192.168.250.1'

- name: Add nrpe.d include dir to nrpe.cfg
  lineinfile: dest=/etc/nagios/nrpe.cfg state=present line='include_dir=/etc/nagios/nrpe.d/'

- name: Copy custom NRPE commands to nrpe.d
  copy: src=/etc/ansible/roles/nrpe/files/my.cfg dest=/etc/nagios/nrpe.d/ owner=nagios group=nagios mode=0644 backup=yes
  notify:
   - Restart NRPE

- name: Copy check_docker to Nagios Plugin directory
  copy: src=/etc/ansible/roles/nrpe/files/check_docker dest=/usr/lib/nagios/plugins/ owner=nagios group=nagios mode=0755

- name: Apt Install Python-PIP
  apt: pkg=python-pip state=installed

- name: PIP Install docker-py
  pip: name=docker-py

- name: PIP Install nagiosplugin
  pip: name=nagiosplugin
