- name: Start Docker Services
  systemd: name=docker state=started
  listen: "Start Docker Services"
  
- name: Restart Docker Services
  systemd: name=docker state=restarted
  listen: "Restart Docker Services"
  
- name: Stop Docker Services
  systemd: name=docker state=stopped
  listen: "Stop Docker Services"