- name: Install system updates for CentOS systems
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install system updates for Ubuntu systems
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  when: ansible_distribution == "Ubuntu"