---

- name: Launch Openshift Origin Container on Docker
  docker:
    name: origin
    image: openshift/origin
    privileged: yes
    net: host
    pid: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/docker:/var/lib/docker:rw
      - /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave
      - /var/log:/var/log