---

- name: Copy Grafana yml file
  template: src=grafana.yml.j2 dest={{ kube_addon_dir }}/grafana.yml

- name: Check Grafana role already exists
  command: kubectl --kubeconfig={{ kubeadmin_config }} get clusterrolebinding | grep monitoring-grafana
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: check_grafana
  ignore_errors: true

- name: Create Grafana Deployment
  when: check_grafana|failed
  shell: kubectl apply --kubeconfig={{ kubeadmin_config }} -f {{ kube_addon_dir }}/grafana.yml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true