---

- name: Copy Heapster yml file
  template: src=heapster.yml.j2 dest={{ kube_addon_dir }}/heapster.yml

- name: Copy Heapstar RBAC yml file
  template: src=heapster-rbac.yml.j2 dest={{ kube_addon_dir }}/heapster-rbac.yml

- name: Check Heapster is working
  shell: kubectl --kubeconfig={{ kubeadmin_config }} get po --all-namespaces | grep heapster
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: check_heap
  ignore_errors: true
  
- name: Create Heapster deployment
  when: check_heap|failed
  shell: |
      kubectl create --kubeconfig={{ kubeadmin_config }} -f {{ kube_addon_dir }}/heapster.yml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true