---

- name: Copy InfluxDB yml file
  template: src=influxdb.yml.j2 dest={{ kube_addon_dir }}/influxdb.yml

- name: Check InFluxDB role already exists
  shell: kubectl --kubeconfig={{ kubeadmin_config }} get clusterrolebinding | grep monitoring-influxdb
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: check_influxdb
  ignore_errors: true

- name: Create InFluxDB Deployment
  when: check_influxdb|failed
  shell: kubectl apply --kubeconfig={{ kubeadmin_config }} -f {{ kube_addon_dir }}/influxdb.yml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Check Heapster role already exists
  shell: kubectl --kubeconfig={{ kubeadmin_config }} get clusterrolebinding | grep heapster
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: check_role_heap
  ignore_errors: true

- name: Create Heapster role
  when: check_role_heap|failed
  shell: kubectl apply --kubeconfig={{ kubeadmin_config }} -f {{ kube_addon_dir }}/heapster-rbac.yml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: create_role_heap
