---

- name: Create Kubernetes addon directory
  file: path={{ kube_addon_dir }} state=directory

- name: Create Kubernetes addon/certs directory
  file: path={{ kube_addon_dir }}/certs state=directory

- include_tasks: grafana.yml
- include_tasks: heapster.yml
- include_tasks: influxdb.yml
- include_tasks: dashboard.yml