---
# file: roles/common/tasks/ssh-keys.yml
- name: Set up authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - roles/common/files/cy-dsktp01.pub
    - roles/common/files/cy-mbp-13-3.pub
    - roles/common/files/taius-main.pub
    - roles/common/files/util01.pub
  tags: ssh-keys