---

- name: Cleanup old docker versions
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=absent
  with_items:
    - docker
    - docker.io
    - docker-common
    - docker-selinux
    - docker-engine

- name: Ensure APT is setup for HTTPS repos (Debian/Ubuntu)
  when: ansible_distribution == "Ubuntu"
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Install required packages for (RHEL/CentOS)
  when: ansible_os_family == "Redhat"
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: 'docker'

- name: Add Docker Repo (RHEL/CentOS)
  when: ansible_os_family == "Redhat"
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker engine (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name: "docker-ce-{{ docker_version }}.el7.centos"
    state: present

- name: Install docker engine (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: "docker-ce={{ docker_version }}*"
    state: present

- name: Hold docker version (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: docker-ce
    selection: hold

- name: Install Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.18/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 0777
