---
# file: roles/webmin/tasks/main.yml
- name: Add Webmin Repo for CentOS
  yum_repository:
    name: Webmin
    description: Webmin Distribution Neutral
    baseurl: https://download.webmin.com/download/yum
    mirrorlist: https://download.webmin.com/download/yum/mirrorlist
    gpgkey: http://www.webmin.com/jcameron-key.asc
    gpgcheck: yes
  when: ansible_distribution == "CentOS"

- name: Add Webmin Key for Ubuntu
  apt_key: url=http://www.webmin.com/jcameron-key.asc state=present
  when: ansible_distribution == "Ubuntu"
  
- name: Add Webmin APT Repo for Ubuntu  
  apt_repository:
    repo: deb https://download.webmin.com/download/repository sarge contrib
    state: present
    filename: 'webmin'
  when: ansible_distribution == "Ubuntu"

- name: Install HTTPS support for APT on Ubuntu
  apt: name=apt-transport-https state=present update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Install Webmin
  action: >
    {{ ansible_pkg_mgr }} name=webmin state=present update_cache=true
  notify: Start Webmin

- name: Copy firewalld service entry for CentOS
  copy: src=roles/webmin/files/webmin.xml dest=/etc/firewalld/services/ owner=root group=root mode=0644
  when: ansible_distribution == "CentOS"

- name: Check state of firewalld and register
  command: /usr/bin/firewall-cmd --state
  ignore_errors: yes
  register: firewalld_state
  when: ansible_distribution == "CentOS"

- name: Check state of UFW and register
  command: "ufw status | grep Status: | sed 's/Status: //g'"
  register: ufw_state
  when: ansible_distribution == "Ubuntu"

- name: Modify firewalld for CentOS
  firewalld: service=webmin zone=public permanent=true immediate=yes state=enabled
  when: 
    - ansible_distribution == "CentOS"
    - firewalld_state == "running"

- name: Modify UFW
  ufw: rule=allow port=10000 proto=tcp src={{ item }}
  with_items:
    - 192.168.52.0/24
    - 192.168.250.0/24
    - 172.16.0.0/12
  when: 
    - ansible_distribution =="Ubuntu"
    - ufw_state == "active"