---

- name: Add Webmin Repo for CentOS
  yum_repository:
    name: Webmin
    description: Webmin Distribution Neutral
    baseurl: https://download.webmin.com/download/yum
    mirrorlist: https://download.webmin.com/download/yum/mirrorlist
    gpgkey: http://www.webmin.com/jcameron-key.asc
    gpgcheck: yes
  when: ansible_distribution == "CentOS"

- name: Add Webmin Key
  apt_key: url=http://www.webmin.com/jcameron-key.asc state=present
  
- name: Add Webmin APT Repo for Ubuntu  
  apt_repository:
    repo: deb https://download.webmin.com/download/repository sarge contrib
    state: present
    filename: 'webmin'
  when: ansible_distribution == "Ubuntu"

- name: Install HTTPS support for APT on Ubuntu
  apt: name=apt-transport-https state=present update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Install Webmin
  action: >
    {{ ansible_pkg_mgr }} name=webmin state=present update_cache=true
  notify: Start Webmin
