---
- name: Add Webmin Apt Keys
  apt_key: url=http://www.webmin.com/jcameron-key.asc state=present

- name: Add Webmin Apt Source
  copy: src=/etc/ansible/roles/webmin/files/webmin.list dest=/etc/apt/sources.list.d owner=root group=root mode=0644 backup=yes
  become: yes

- name: Install Webmin
  apt: pkg=webmin state=latest update_cache=true
  notify: Start Webmin
