---

- name: "Set fact {{ network }} cni variable"
  set_fact:
    cni: "{{ vars[network] }}"

- name: "Check {{ cni.name }} cluster role already exists"
  shell: kubectl --kubeconfig={{ kubeadmin_config }} get clusterrole | grep {{ cni.name }}
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: check_role
  ignore_errors: true

- name: "Create {{ cni.name }} cluster role"
  when: 
    - check_role|failed
    - network == "flannel"
  command: kubectl apply --kubeconfig={{ kubeadmin_config }} -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: create_role

- name: "Create {{ cni.name }} cluster role"
  when: 
    - check_role|failed
    - network == "weave"
  command: kubectl apply --kubeconfig={{ kubeadmin_config }} -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: create_role

- name: "Create {{ cni.name }} cluster role"
  when: 
    - check_role|failed
    - network == "calico"
  command: kubectl apply --kubeconfig={{ kubeadmin_config }} -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: create_role

- name: "Create {{ cni.name }} cluster role"
  when: 
    - check_role|failed
    - network == "kube_router"
  command: kubectl apply --kubeconfig={{ kubeadmin_config }} -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: create_role

- name: "Create {{ cni.name }} cluster role"
  when: 
    - check_role|failed
    - network == "romana"
  command: kubectl apply --kubeconfig={{ kubeadmin_config }} -f https://raw.githubusercontent.com/romana/romana/master/containerize/specs/romana-kubeadm.yml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: create_role